version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx1g"
      ELASTIC_PASSWORD: $ELASTICSEARCH_PASSWORD
      xpack.security.enabled: $ELASTIC_SECURITY
      TZ: $TIMEZONE
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200/tcp

volumes:
  esdata: