version: "3"

services:
  kibana:
    environment:
      VIRTUAL_HOST: $KIBANA_HOSTNAME
      VIRTUAL_PORT: 5601
      LETSENCRYPT_HOST: $KIBANA_HOSTNAME

networks:
  default:
    external:
      name: nginx-proxy