version: "3"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
      ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD
      TZ: $TIMEZONE
    ports:
      - 5601:5601/tcp