filebeat.config:
  inputs:
    enabled: true
    path: inputs.d/*.yml
    reload.enabled: true
    reload.period: 10s
  modules:
    enabled: true
    path: modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

output:
  elasticsearch:
    hosts: '${ELASTICSEARCH_URL}'
    username: '${ELASTICSEARCH_USERNAME}'
    password: '${ELASTICSEARCH_PASSWORD}'
    indices:
      - index: "app-filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
